// Generates src/lib/provisioning/box-agent-embed.ts from the on-box agent
// source + systemd unit, so the Next bundler reliably inlines them into the
// provisioner (reading files at runtime is unreliable under bundling).
//
// Run: node box-agent/gen-embed.mjs   (also wired as `npm run gen:box-agent`)

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const agent = readFileSync(join(here, 'agent.mjs'), 'utf8');
const service = readFileSync(join(here, 'appie-agent.service'), 'utf8');

// Embed as base64 to survive every layer of quoting (heredoc, YAML, JSON).
const out = [
  '// AUTO-GENERATED by box-agent/gen-embed.mjs. Do not edit by hand.',
  '// Source of truth: box-agent/agent.mjs + box-agent/appie-agent.service.',
  '// Re-run `npm run gen:box-agent` after changing those files.',
  '',
  `export const BOX_AGENT_SOURCE_B64 = ${JSON.stringify(Buffer.from(agent).toString('base64'))};`,
  '',
  `export const BOX_AGENT_SERVICE_B64 = ${JSON.stringify(Buffer.from(service).toString('base64'))};`,
  '',
].join('\n');

const dest = join(here, '..', 'src', 'lib', 'provisioning', 'box-agent-embed.ts');
writeFileSync(dest, out);
process.stdout.write(`wrote ${dest} (agent ${agent.length}b, service ${service.length}b)\n`);
